name: diary_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  change_app_package_name: ^1.4.0
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  get_it: ^8.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Alegreya Sans SC
      fonts:
        - asset: fonts/AlegreyaSans-Regular.ttf
