import 'package:flutter/material.dart';

const kBlack = Colors.black;
const kWhite = Colors.white;
const kGrey = Colors.grey;
const kYellow = Colors.yellow;
const kRed = Colors.red;
const kTransparent = Colors.transparent;
const kGreen = Colors.green;
const kLightYellowColor = Color.fromARGB(255, 255, 224, 133);
const kAmber = Colors.amber;
const kPurple = Colors.purple;
const kPink = Color(0xFFFFC0CB);
const kPinkFade = Color.fromARGB(255, 245, 210, 216);
const kCustomPink200 = Color(0xFFF48FB1);
const kCustomGreen100 = Color(0xFFC8E6C9);
const kCustomBlue100 = Color(0xFFBBDEFB);
const kCustomPink100 = Color(0xFFF8BBD0);
Color kFadedYellow = Colors.yellow[100]!;
const kdarkerRed = Color.fromARGB(255, 171, 62, 80);
